version: '3'

services:
  workouts:
    image: workouts/workouts:local
    build:
      context: .
    environment:
      RACK_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
    extra_hosts:
      # Allow accessing services running on `localhost`, outside the container
      - host.docker.internal:host-gateway
    ports:
      # HOST:CONTAINER
      - 8080:8080
    volumes:
      - .:/server
